# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=20)),
                ('birth_date', models.DateField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('mobile_no', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=20)),
                ('current_year', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
