# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_AddProfileModel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={},
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='admission_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
