# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_userprofilemodel_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='mobile_no',
        ),
    ]
