# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190212_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='address',
        ),
    ]
