# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_userprofilemodel_mobile_no'),
    ]

    operations = [
        
    ]
