# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_userprofilemodel_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
