# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_userprofilemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
