# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_userprofilemodel_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='date2',
        ),
    ]
