# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20190212_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
