# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_userprofilemodel_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='current_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
