# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20190212_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
