# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_userprofilemodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='middel_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
