# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_userprofilemodel_middel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='middel_name',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
