# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20190213_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8),
        ),
    ]
