# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-14 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_userprofilemodel_imsge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='imsge',
            new_name='image',
        ),
    ]
