# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20190214_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
