# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-15 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_auto_20190315_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='examform',
            name='current_year',
            field=models.CharField(choices=[('second year', 'second year'), ('third year', 'third year')], max_length=20, null=True),
        ),
    ]
