# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_examform_current_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='examform',
            name='semister',
            field=models.CharField(choices=[('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=20, null=True),
        ),
    ]
