# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_examform_semister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examform',
            name='roll_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
