# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-18 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20190318_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='mobile_no',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
