# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-24 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0041_regularrevalutionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='atktrevalutionmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('exam_type', models.CharField(choices=[('CBCS', 'CBCS'), ('CBGS', 'CBGS')], max_length=100)),
                ('semister', models.CharField(choices=[('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=20, null=True)),
                ('seat_no', models.IntegerField(default=0, null=True)),
                ('last_seat_no', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
