# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-25 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0044_examcelladmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='consessionadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('mobile_no', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
