# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0048_auto_20190326_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='examformmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField(default=0, null=True)),
                ('admission_no', models.CharField(max_length=60, null=True)),
                ('branch', models.CharField(choices=[('information technology', 'information technology'), ('computer engineering', 'computer engineering'), ('production engineering', 'production engineering'), ('mechanical engineering', 'mechanical engineering'), ('chemical engineering', 'chemical engineering'), ('electronics & telecommunication engineering', 'electronics & telecommunication engineering')], max_length=100, null=True)),
                ('current_year', models.CharField(choices=[('second year', 'second year'), ('third year', 'third year')], max_length=20, null=True)),
                ('semister', models.CharField(choices=[('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='examform',
            name='user',
        ),
        migrations.DeleteModel(
            name='examform',
        ),
    ]
