# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_auto_20190327_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='examformmodel',
            new_name='examform',
        ),
    ]
