# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_auto_20190327_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examform',
            name='user',
        ),
        migrations.DeleteModel(
            name='examform',
        ),
    ]
