# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_examform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='examform',
            new_name='examformmodel',
        ),
    ]
