# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0053_auto_20190328_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='mobile_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
