# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0054_auto_20190402_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Branch')),
            ],
        ),
        migrations.RemoveField(
            model_name='examformmodel',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='examformmodel',
            name='semister',
        ),
        migrations.AlterField(
            model_name='examformmodel',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Branch'),
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Year'),
        ),
    ]
