# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_auto_20190402_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
