# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0056_auto_20190403_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Year')),
            ],
        ),
    ]
