# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0058_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Semester'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
