# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0059_auto_20190403_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examformmodel',
            old_name='name',
            new_name='subject',
        ),
    ]
