# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0060_auto_20190403_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='branch',
        ),
    ]
