# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-15 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0063_auto_20190408_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularrevalutionmodel',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='regularrevalutionmodel',
            name='semister',
        ),
        migrations.AddField(
            model_name='regularrevalutionmodel',
            name='admission_no',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='regularrevalutionmodel',
            name='branch',
            field=models.CharField(choices=[('information technology', 'information technology'), ('computer engineering', 'computer engineering'), ('production engineering', 'production engineering'), ('mechanical engineering', 'mechanical engineering'), ('chemical engineering', 'chemical engineering'), ('electronics & telecommunication engineering', 'electronics & telecommunication engineering')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='regularrevalutionmodel',
            name='roll_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='regularrevalutionmodel',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Semester'),
        ),
        migrations.AddField(
            model_name='regularrevalutionmodel',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Year'),
        ),
    ]
