# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_auto_20190415_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularrevalutionmodel',
            name='seat_no',
        ),
        migrations.AddField(
            model_name='regularrevalutionmodel',
            name='last_seat_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='atktmodel',
            name='last_seat_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
