# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0066_auto_20190415_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularrevalutionmodel',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
