# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-16 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0068_auto_20190415_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcelladmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examcelladminprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
