# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0073_auto_20190419_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examformmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='subject',
            field=models.ManyToManyField(null=True, to='student.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Semester'),
        ),
    ]
