# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0074_auto_20190419_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examformmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='subject1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='subject2',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
