# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0075_auto_20190420_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='examformmodel',
            name='subject3',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='subject4',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='subject5',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='subject6',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
