# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0076_auto_20190420_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='atktmodel',
            name='subject1',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktmodel',
            name='subject2',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktmodel',
            name='subject3',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktmodel',
            name='subject4',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktmodel',
            name='subject5',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktmodel',
            name='subject6',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
