# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0077_auto_20190420_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atktmodel',
            name='last_seat_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='atktmodel',
            name='subject1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='atktmodel',
            name='subject2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='atktmodel',
            name='subject3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='atktmodel',
            name='subject4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='atktmodel',
            name='subject5',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='atktmodel',
            name='subject6',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
