# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0078_auto_20190420_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atktmodel',
            name='subject',
        ),
        migrations.AlterField(
            model_name='examformmodel',
            name='subject1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='examformmodel',
            name='subject2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='examformmodel',
            name='subject3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='examformmodel',
            name='subject4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='examformmodel',
            name='subject5',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='examformmodel',
            name='subject6',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
