# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0081_auto_20190420_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atktrevalutionmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='atktrevalutionmodel',
            name='subject1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktrevalutionmodel',
            name='subject2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktrevalutionmodel',
            name='subject3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktrevalutionmodel',
            name='subject4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktrevalutionmodel',
            name='subject5',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='atktrevalutionmodel',
            name='subject6',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
