# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0082_auto_20190420_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atktrevalutionmodel',
            name='admission_no',
        ),
    ]
