# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0083_remove_atktrevalutionmodel_admission_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularphotocopymodel',
            name='admission_no',
        ),
        migrations.RemoveField(
            model_name='regularphotocopymodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='regularphotocopymodel',
            name='subject1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='regularphotocopymodel',
            name='subject2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='regularphotocopymodel',
            name='subject3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='regularphotocopymodel',
            name='subject4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='regularphotocopymodel',
            name='subject5',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='regularphotocopymodel',
            name='subject6',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
