# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0085_auto_20190420_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consessionformmodel',
            old_name='last_ticket_form',
            new_name='last_ticket_from',
        ),
    ]
