# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-20 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0086_auto_20190420_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consessionformmodel',
            name='to_date',
        ),
    ]
