# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0093_atktmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atktmodel',
            name='amount',
        ),
        migrations.AddField(
            model_name='atktmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default=3),
        ),
    ]
