# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0094_auto_20190424_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='atktphotocopymodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default=3),
        ),
        migrations.AddField(
            model_name='atktrevalutionmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default=3),
        ),
        migrations.AddField(
            model_name='regularphotocopymodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected'), (3, 'Pending')], default=3),
        ),
    ]
