# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0095_auto_20190425_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consessionformmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='newconsessionformmodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='consessionformmodel',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='newconsessionformmodel',
            name='from_date',
            field=models.DateField(null=True),
        ),
    ]
