# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0096_auto_20190425_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcelladmin',
            name='branch',
            field=models.CharField(choices=[('information technology', 'information technology'), ('computer engineering', 'computer engineering'), ('production engineering', 'production engineering'), ('mechanical engineering', 'mechanical engineering'), ('chemical engineering', 'chemical engineering'), ('electronics & telecommunication engineering', 'electronics & telecommunication engineering')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examcelladmin',
            name='result',
            field=models.FileField(default=datetime.datetime(2019, 4, 25, 14, 34, 30, 524576, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
