# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0097_auto_20190425_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcelladmin',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='examcelladmin',
            name='result',
        ),
    ]
