# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0098_auto_20190425_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('information technology', 'information technology'), ('computer engineering', 'computer engineering'), ('production engineering', 'production engineering'), ('mechanical engineering', 'mechanical engineering'), ('chemical engineering', 'chemical engineering'), ('electronics & telecommunication engineering', 'electronics & telecommunication engineering')], max_length=200, null=True)),
                ('result', models.FileField(upload_to='')),
            ],
        ),
    ]
