# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0099_uploadresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadresult',
            name='result',
            field=models.FileField(upload_to='documents'),
        ),
    ]
