# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0101_uploadresult_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadresult',
            new_name='uploadresultmodel',
        ),
    ]
