# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0102_auto_20190425_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadresultmodel',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
