# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-28 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0105_uploadnoticemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadnoticemodel',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2019, 4, 28, 11, 48, 50, 801494, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
