# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0106_uploadnoticemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consessionadmin',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
