# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0109_auto_20190922_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
