# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-22 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0110_auto_20190922_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examformmodel',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='examformmodel',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='examformmodel',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='examformmodel',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='examformmodel',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='examformmodel',
            name='subject6',
        ),
        migrations.AddField(
            model_name='examformmodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Subject'),
        ),
    ]
