# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0116_auto_20190924_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atktmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='atktmodel',
            name='subject',
            field=models.ManyToManyField(null=True, to='student.Subject'),
        ),
    ]
