# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0117_auto_20190924_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atktmodel',
            name='subject',
            field=models.ManyToManyField(to='student.Subject'),
        ),
    ]
