# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0119_auto_20190924_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='selectedsubject',
            name='subject',
        ),
        migrations.AlterField(
            model_name='subject_multiple',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Semester'),
        ),
        migrations.DeleteModel(
            name='SelectedSubject',
        ),
    ]
