# Generated by Django 2.2.5 on 2019-09-25 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0121_atktmodel_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atktmodel',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject_multiple',
            name='name',
        ),
    ]
