# Generated by Django 2.2.5 on 2019-09-25 02:45

from django.db import migrations
import multiselectfield.db.fields
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0123_auto_20190925_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atktmodel',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, null=True, verbose_name=student.models.Subject),
        ),
        migrations.AlterField(
            model_name='subject_multiple',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[['applied physics 1', 'applied physics 1'], ['M3', 'M3']], max_length=20, null=True),
        ),
    ]
