# Generated by Django 2.2.5 on 2019-09-25 03:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0125_auto_20190925_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atktmodel',
            name='subject',
        ),
        migrations.AlterField(
            model_name='atktmodel',
            name='IT_FE_2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Applied Mathematics – II', 'Applied Mathematics – II'), ('Applied Physics – II', 'Applied Physics – II'), ('Applied Chemistry – II\t', 'Applied Chemistry – II'), ('Introduction to Programming', 'Introduction to Programming'), ('Engineering Mechanics', 'Engineering Mechanics'), ('Electrical Science', 'Electrical Science')], max_length=138, null=True),
        ),
    ]
